Player UI, setting UI, player class
CMPUT301W23T48/QR-Ranger pull request #49
Opened 2023-03-09 01:19 UTC by minhalo113

2023-03-09 01:22 UTC, ncusimano approved these changes
Thanks!

2023-03-09 01:22 UTC, JFong5 approved these changes

2023-03-09 03:40 UTC, fuzzydomo approved these changes
yep looks great!

2023-03-09 06:59 UTC, LostLittleKiddo approved these changes

2023-03-09 21:07 UTC, ajboman requested changes

2023-03-09 21:07 UTC, ajboman commented on app/src/main/java/com/example/qrranger/MainActivity.java
> -package com.example.qrranger;
This is not up to date with the `main` branch. The `MainActivity.java` file in main is populated. See this: 

https://github.com/CMPUT301W23T48/QR-Ranger/blob/main/app/src/main/java/com/example/qrranger/MainActivity.java#L1

I believe you should merge main into this branch first and then we can merge this PR.

Same thing for `activity_main.xml`

2023-03-09 22:58 UTC, JFong5 approved these changes

2023-03-09 23:56 UTC, LostLittleKiddo requested changes
Dont delete java doc

2023-03-10 00:33 UTC, ncusimano requested changes
The MainActivity is deleted.

2023-03-12 03:09 UTC, closed without merging